config/routes.rb
Rails.application.routes.draw do
  resources :connections
  resources :airline_connections
  resources :airlines
  resources :bookings
  resources :travellers
  resources :login, only: [:new, :create]
  delete "/logout", to: "login#destroy", as: "logout"
  post '/airline_connections/choose', to: 'airline_connections#choose'
  post '/connections/choose', to: 'connections#choose'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/airline.rb
class Airline < ApplicationRecord
  has_many :airline_connections
  has_many :connections, through: :airline_connections
end

app/models/airline_connection.rb
class AirlineConnection < ApplicationRecord
  belongs_to :connection
  belongs_to :airline

  def full_connection
    "#{self.connection.location_1} to #{self.connection.location_2} with #{self.airline.name} for $#{self.price}"
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :traveller
  belongs_to :connection

end

app/models/connection.rb
class Connection < ApplicationRecord
  has_many :airline_connections
  has_many :airlines, through: :airline_connections
  has_many :bookings
  has_many :travellers, through: :bookings


  def full_connection
    "#{location_1} to #{location_2}"
  end

  def booking_details
    "#{self.location_1} to #{self.location_2}"
  end




end

app/models/traveller.rb
class Traveller < ApplicationRecord
  has_many :bookings
  has_many :connections, through: :bookings

  validates :name, presence: true
  validates :username, uniqueness: true
  validates :username, presence: true
  validates :password, length: {in: 4..20}

  has_secure_password
end

app/controllers/airline_connections_controller.rb
class AirlineConnectionsController < ApplicationController


  def index
    @airline_connections = AirlineConnection.all
  end

  def show

    @airline_connection = AirlineConnection.find(params[:id])
    @booking = Booking.new
  end

  def choose
  @airline_connection = AirlineConnection.find(params[:chosen_airline_connection])
  redirect_to @airline_connection
  end

end


# def choose
# @airline_connection = AirlineConnection.find(params[:chosen_airline_connection])
# redirect_to new_booking_path(connection: @airline_connection.connection_id)
# end

app/controllers/airlines_controller.rb
class AirlinesController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_up_voting

private

  def set_up_voting
      # session["remaining_votes"] ||= 5
      @notification = flash["notification"]
      @errors = flash["errors"]
      # byebug
    if (session[:traveller_id])
      @logged_in_traveller = Traveller.find(session[:traveller_id])

    end
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def index

  end

  def new
    @booking = Booking.new
    @airline_connection = AirlineConnection.new
  end

  def create
    @traveller = session[:traveller_id]
    @booking = Booking.create(booking_params)
    redirect_to traveller_path(Traveller.find(@booking.traveller_id))
  end

  def show
    @booking = Booking.find(params[:id])
  end

  def destroy
    @traveller = session[:traveller_id]
    @booking= Booking.find(params[:id])
    @booking.destroy
    redirect_to traveller_path(@traveller)
  end


  private
  def booking_params
    params.require(:booking).permit(:date, :traveller_id, :connection_id)
  end



end

app/controllers/connections_controller.rb
class ConnectionsController < ApplicationController
  def index
    @connections = Connection.all
  end

  def show
    @connection = Connection.find(params[:id])
  end

  def choose
  @connection = Connection.find(params[:chosen_connection])
  redirect_to airline_connection_url(connection: @connection)
  end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController

  def new

  end

  def create
    traveller = Traveller.find_by(username: params[:username])
    if traveller && traveller.authenticate(params[:password])
      session[:traveller_id] = traveller.id
      redirect_to traveller_path(traveller)
    else
      flash[:errors] = ["Ya done goofed"]
      redirect_to new_login_path
    end
  end

  def destroy
    session[:traveller_id] = nil
    flash[:message] = ["You've been logged out"]
   redirect_to travellers_path
  end



end

app/controllers/travellers_controller.rb
class TravellersController < ApplicationController
  def index
    
  end

   def new
      @traveller = Traveller.new
   end

   def create
     @traveller = Traveller.new(traveller_params)
     if @traveller.save
       session[:traveller_id] = @traveller.id
       redirect_to @traveller
     else
       flash[:errors] = @traveller.errors.full_messages
       flash[:attributes] = @traveller.attributes
       redirect_to new_traveller_path
     end
   end

   def show
     @traveller = Traveller.where(id: params[:id]).first
    unless @logged_in_traveller && @logged_in_traveller == @traveller
      flash[:errors] = ["You don't have permission to see that page"]
      redirect_to traveller_path(@logged_in_traveller)
    end
   end

   private

   def traveller_params
     params.require(:traveller).permit(:name, :username, :password)
   end
end

app/helpers/airline_connections_helper.rb
module AirlineConnectionsHelper
end

app/helpers/airlines_helper.rb
module AirlinesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/connections_helper.rb
module ConnectionsHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/travellers_helper.rb
module TravellersHelper
end

app/views/airline_connections/index.html.erb
<div class="all-flights">
<%= form_tag("/airline_connections/choose") do %>
<p class="select-button"> Select flight<%= select_tag "chosen_airline_connection", options_from_collection_for_select(AirlineConnection.all, "id", "full_connection" ) %> </p>
  <%= submit_tag "See Option" %>
<% end %>

<%= link_to "Go back to your profile", traveller_path(session[:traveller_id]) %>
</div>

app/views/airline_connections/show.html.erb
<div class="select-flight">
<%= "Airline: #{@airline_connection.airline.name} Departure: #{@airline_connection.connection.location_1}, Arrival: #{@airline_connection.connection.location_2} Price: $#{@airline_connection.price}"%>
<br>

<%=form_for @booking do |f| %>

  <%= f.hidden_field :traveller_id, value: session[:traveller_id] %>

  <%=  f.hidden_field :connection_id, value: @airline_connection.connection_id%>

  <%= f.label :date %>
  <%= f.date_field :date %>

  <%= f.submit "Create Booking" %>
<% end %>


<%= link_to "Go back to see other flights", airline_connections_path %>
</div>

app/views/bookings/show.html.erb
<div class="traveller-booking">

<%= "#{@booking.connection.full_connection} on #{@booking.date}" %>

<%= button_to "Delete this Booking", @booking, method: :delete %>

<% if session[:traveller_id] %>
<%= link_to "See your profile", traveller_path(session[:traveller_id]) %>
<% end %>
</div>

app/views/connections/index.html.erb
<%= form_tag("/connections/choose") do %>
<p> Departure  <%= select_tag "chosen_connection", options_from_collection_for_select(Connection.all, "id", "location_1") %>
  <%= submit_tag "See Option" %>
<% end %>

<%= form_for @connection do |f| %>
<%= f.label :connection %>
<%= f.collection_select(:connection_id, Connection.all, :id, :location_1) %>
<%= f.submit "Submit" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BDTripPlannerApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Quicksand&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Bad+Script&display=swap" rel="stylesheet">
  </head>

  <body>
  <div class="clearfix">
    <div class="menu-bar">
      <div class="log-out">
    <% if session[:traveller_id] %>
       <%= button_to "Log-out", logout_path, method: :delete %>
    <% end %>
    </div>

    <% unless session[:traveller_id] %>
       <%= link_to "Click here to Log-in", new_login_path %>
       <%= link_to "Click here to Sign-up", new_traveller_path %>
    <% end %>
    </div>
  </div>

    <% if session[:traveller_id] %>
      <h1>Welcome to BD Travel App <span style="color:red"> <%= Traveller.find(session[:traveller_id]).name %> <span></h1>
      <%  else %>
        <h1>Welcome to BD Travel App</h1>
      <% end %>


    <%= yield %>
  </body>
</html>

app/views/login/new.html.erb
<%= form_tag login_index_path do %>
  <% if flash[:errors] %>
  <% flash[:errors].each do |error| %>
  <%= error %>
  <% end %>
<% end %>

<div class="login">
    <ul>
    <li>
      <%= label_tag :username %>
      <%= text_field_tag :username %>
    </li>
    <li>
      <%= label_tag :password %>
      <%= password_field_tag :password %>
    </li>
  </ul>
  <span class="submit">
  <%= submit_tag "Log in" %>
  </span>
<% end %>
</div>

app/views/travellers/index.html.erb
  <p class="logout-message"><% if flash[:message] %>
  <% flash[:message].each do |message| %>
  <%= message %>
  <%end%>
  <% else %>
  <%= "Taking care of all your travel needs!" %>
  <% end %>
  </p>


<% if session[:traveller_id] %>
<%= link_to "See your profile", traveller_path(session[:traveller_id]) %>
<% end %>

app/views/travellers/new.html.erb
<div class="new-traveller">


<h2>Create a new account</h2>
  <% if flash[:errors] %>
    <% flash[:errors].each do |error| %>
      <%= error %>
    <% end %>
  <% end %>


<%= form_for @traveller do |f|%>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :username %>
  <%= f.text_field :username %>
  <%= f.label :password %>
  <%= f.password_field:password %>
  <%= f.submit "Create a new account" %>
  <% end %>

  </div>

app/views/travellers/show.html.erb
  <% if flash[:errors] %>
  <% flash[:errors].each do |error|  %>
  <%= error %>
  <% end %>
  <% end %>

<div class="traveller-show-page">
<% if !@traveller.bookings.empty?  %>
<p class="flights"> <%= "Here are all your booked flights 🛩:"%></p>

  <% @traveller.bookings.each do |booking| %>
    <li><%= link_to "#{booking.connection.booking_details} on #{booking.date}", booking_path(booking) %></li>
  <% end %>
<% else %>
<p><%= "You have no flights!" %></p>


<% end %>

<div class="link-to-airline-connection">
<%= link_to "See all flights", airline_connections_path %>
</div>

</div>